package general.montiarcexample;

language component AutomatenArchitekturLanguageProduct {

  grammar mc.lang.MontiArcWithStateChartsWithVariable;

  provides production Komponente for Component;

  requires optional production Verhalten for BehaviorElement;

  requires optional production Invariante for MontiArcInvariant;

  wfrs BasicCocos for Connector {
    mc.lang.montiarc.cocos.ConnectorSourceAndTargetExistAndFit;
  }

  wfrs NoInnerComponents for Component {
    mc.lang.montiarc.cocos.PreventInnerComponents;
  }

  gen context general.montiarcexample.montiarc._generator.MA2Java;
  gen context general.montiarcexample.montiarc._generator.MAInv2Java;

  provides gen Komponente2Java for Component {
    producer general.montiarcexample.montiarc._generator.MA2Java.IMontiArc2JavaGenerator;
    product general.montiarcexample.montiarc._generator.MA2Java.IComponent;
  }

  requires optional gen Verhalten2Java for BehaviorElement {
    producer general.montiarcexample.montiarc._generator.MA2Java.IBehaviorGen;
    product general.montiarcexample.montiarc._generator.MA2Java.IComputable;
  }

  requires optional gen Invariante2Java for MontiArcInvariant {
    producer general.montiarcexample.montiarc._generator.MAInv2Java.IMAInvGen;
    product general.montiarcexample.montiarc._generator.MAInv2Java.MAInvChecker;
  }

  parameter optional int max for wfr general.montiarcexample.statecharts.cocos.NumInitialStates;

  requires optional production Var for SCElement;

  gen context general.montiarcexample.statecharts._generator._producer.SCElement2JavaProducer;
  gen context general.montiarcexample.statecharts._generator._product.SCElement2JavaProduct;

  requires optional gen SCElementTrafo for SCElement {
    producer general.montiarcexample.statecharts._generator._producer.SCElement2JavaProducer.ISCElement2Java;
    product general.montiarcexample.statecharts._generator._product.SCElement2JavaProduct.ISCElementBehavior;
  }

  gen context general.montiarcexample.variable._generator._producer.VarTrafosProducer;
  gen context general.montiarcexample.variable._generator._product.VarTrafosProduct;

  requires mandatory gen VarTrafo for VariableDefinition {
    producer general.montiarcexample.variable._generator._producer.VarTrafosProducer.IVarGen;
    product general.montiarcexample.variable._generator._product.VarTrafosProduct.IVariable;
  }

}
