package sc.charguard;

import sc.charguard._generator.CharacterGeneratorDomain.*;
import sc.character.cocos.*;

language component CharGuard {
  grammar sc.Character;

  provides production Character for CharacterRule;

  provides gen CharacterGenerator for CharacterRule {
    generator CharacterGenerator;
    producer ICharacterGenerator;
    product ICharacter;
  }

  wfrs UpperCaseCharacters for CharacterRule {
    CharactersUpperCase;
  }
}