package general.montiarcexample.variable;

import general.montiarcexample.variable._generator._producer.VarTrafosProducer.*;
import general.montiarcexample.variable._generator._product.VarTrafosProduct.*;

language component Var {

  grammar mc.lang.Variable;

  provides production Var for VariableDefinition;

  requires mandatory gen VarTrafo for VariableDefinition {
    producer general.montiarcexample.variable._generator._producer.VarTrafosProducer.IVarGen;
    product general.montiarcexample.variable._generator._product.VarTrafosProduct.IVariable;
  }

  provides gen VarGenerator for VariableDefinition {
    producer general.montiarcexample.variable._generator._producer.VarTrafosProducer.IVariableTrafo;
    product general.montiarcexample.variable._generator._product.VarTrafosProduct.IVariable;
  }

  VarGenerator implies VarTrafo;
}
