/*
 * generated by Xtext 2.32.0
 */
package aut.validation;

import org.eclipse.xtext.validation.Check;
import org.xtext.example.automatonLang.IState;
import org.xtext.example.automatonLang.Transition;

/**
 * This class contains custom validation rules.
 *
 * See
 * https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class AutomatonLangValidator extends AbstractAutomatonLangValidator {

	private int counter = 0;

	private Integer maxNumberOfStates = 5;

	@Check
	public void check(IState state) {
		if (state.getInitial() == null || state.getInitial().isEmpty()) {
			counter += 1;
			if (counter > maxNumberOfStates) {
				error("Too many initial states!", null);
			}
		}
	}
	
	@Check
	public void checkNoSelfLoops(Transition trans) {
	    if(trans.getSource().equals(trans.getTarget())) {
			error("No self loops allowed!", null);
	    }

	}
	
}
