/*
 * generated by Xtext 2.32.0
 */
package character.validation;

import org.eclipse.xtext.validation.Check;

import charexpr.charExpression.CharacterRule;

/**
 * This class contains custom validation rules.
 *
 * See
 * https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class CharExpressionValidator extends AbstractCharExpressionValidator {

	@Check
	public void checkCharactersUpperCase(CharacterRule characterRule) {
		if (!Character.isLowerCase(characterRule.getExpr().charAt(0))) {
			error("Characters should be only given in upper case.", null);
		}
	}

}
