package characterexpression;

import characterexpression._generator.CharacterGeneratorDomain.*;
import characterexpression.characterexpression.cocos.*;

language component CharExpr {
  grammar characterexpression.CharacterExpression;

  provides production CharAdaption for CharacterRule; // use this for testing and aggregate to aut

  provides gen CharacterGenerator for CharacterRule {
    generator CharacterGenerator;
    producer ICharacterGenerator;
    product ICharacter;
  }

  wfrs UpperCaseCharacters for CharacterRule {
    CharactersUpperCase;
  }
  
}