/*
 * generated by Xtext 2.32.0
 */
package postact.validation;

import org.eclipse.xtext.validation.Check;

import postact.postAction.Post;

/**
 * This class contains custom validation rules.
 *
 * See
 * https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class PostActionValidator extends AbstractPostActionValidator {

	@Check
	public void checkTweetsAreNoDirectMessages(Post post) {
		String message = post.getMsg();
		if (message.charAt(0) == '@') {
			error("Tweets beginning with an @ character will be interpreted as direct message instead. Use 'dm <msg>' instead.",
					null);
		}

	}

}
