package general.montiarcexample.montiarc;

import general.montiarcexample.montiarc._generator.MA2Java.*;
import general.montiarcexample.montiarc._generator.MAInv2Java.*;
import general.montiarcexample.variable._generator._producer.VarTrafosProducer.*;
import general.montiarcexample.variable._generator._product.VarTrafosProduct.*;

language component SomeNewLanguageComponentCustomized{

  grammar mc.lang.MontiArcWithStateChartsWithVariableWithOCLInvariant;

  provides production Komponente for Component;

  requires optional production Verhalten for BehaviorElement;

  requires optional production Invariante for MontiArcInvariant;

  wfrs BasicCocos for Connector {
    mc.lang.montiarc.cocos.ConnectorSourceAndTargetExistAndFit;
  }

  wfrs NoInnerComponents for Component {
    mc.lang.montiarc.cocos.PreventInnerComponents;
  }

  provides gen Komponente2Java of
      Component with {
    producer IMontiArc2JavaGenerator;
    product IComponent;
  }

  requires requires optional gen Verhalten2Java of
      BehaviorElement with {
    producer IBehaviorGen;
    product IComputable;
  }

  requires requires optional gen Invariante2Java of
      MontiArcInvariant with {
    producer IMAInvGen;
    product MAInvChecker;
  }

  parameter optional int max for wfr general.montiarcexample.statecharts.cocos.NumInitialStates;

  requires optional production Var for SCElement;

  requires requires optional gen SCElementTrafo of
      SCElement with {
    producer ISCElement2Java;
    product ISCElementBehavior;
  }


  requires requires mandatory gen VarTrafo of
      VariableDefinition with {
    producer IVarGen;
    product IVariable;
  }

}
