package general.montiarcexample.montiarc;

import general.montiarcexample.montiarc._generator.MA2Java.*;
import general.montiarcexample.montiarc._generator.MAInv2Java.*;

language component MontiArc {
  grammar mc.lang.MontiArc;

  provides production MACompUnit for MACompilationUnit;
  provides production Komponente for Component;

  requires mandatory production Verhalten for BehaviorElement;
  requires optional production Invariante for Element;

  wfrs BasicCoCos for Connector {
    general.montiarcexample.montiarc.cocos.ConnectorSourceAndTargetExistAndFit;
  }

  wfrs NoInnerComponents for Component {
    general.montiarcexample.montiarc.cocos.PreventInnerComponents;
  }

  provides gen Komponente2Java for Component {
    producer IMontiArc2JavaGenerator;
    product IComponent;
  }

  requires mandatory gen Verhalten2Java for BehaviorElement {
    producer IBehaviorGen;
    product  IComputable;
  }

  requires optional gen Invariante2Java for Element{
    producer IMAInvGen;
    product  MAInvChecker;
  }

  MACompUnit implies Verhalten;
  MACompUnit implies Verhalten2Java;
  MACompUnit implies Invariante;
  MACompUnit implies Invariante2Java;

  Komponente implies Verhalten;
  Komponente implies Verhalten2Java;
  Komponente implies Invariante;
  Komponente implies Invariante2Java;

  Komponente2Java implies Invariante2Java;
  Komponente2Java implies Verhalten2Java;
}
