/*
 * generated by Xtext 2.32.0
 */
package timed.validation;

import org.eclipse.xtext.validation.Check;

import timedexpr.timedExpression.ClockExpr;

/**
 * This class contains custom validation rules.
 *
 * See
 * https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class TimedExpressionValidator extends AbstractTimedExpressionValidator {


	@Check
	public void checkNoNegativeTime(ClockExpr expr) {
		if (expr.getTime().getHours() < 0 || expr.getTime().getMinutes() < 0) {
			error("The given time must not be negative.", null);
		}
	}

}
