/*
* This file was generated by the Gradle 'init' task.
*
* This project uses @Incubating APIs which are subject to change.
*/
pluginManagement {
repositories {
maven {
url = uri("https://nexus.se.rwth-aachen.de/content/groups/public/")
}
gradlePluginPortal()
}
plugins { // added to fix problems with multiple mc versions in path
id 'monticore' version '7.5.0'
}
}

rootProject.name = '${project_name}'